DO NOT MERGE: try bumping eksctl and kubectl
hitting the:
  error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
issue, which seems to be due to kubeconfig specifying wrong api version.

Testing if downgrading helm fixes the issue.

Signed-off-by: Jussi Maki <jussi@isovalent.com>